version: '3'
services:
  bot_service:
    build: ./bot_service
    container_name: telegram_bot_service
    restart: on-failure
    env_file:
      - ./bot_service/.env
    ports:
      - 8001:8000
      - 443:443
