version: '3'
services:
  bot_service:
    build: ./bot_service
    container_name: telegram_bot_service
    restart: on-failure
    env_file:
      - ./bot_service/.env
    command: bash -c "make"
    volumes:
      - ./bot_service/bot:/app/bot
    ports:
      - 8001:8000
      - 443:443

  redis_service:
    image: redis:6
    container_name: redis_service
    command: redis-server --appendonly yes
    volumes:
      - ./redis_service:/data
    restart: on-failure
    ports:
      - 6379:6379
