version: '3'
services:
  bot_service:
    build: ./bot_service
    container_name: telegram_bot_service
    restart: on-failure
    env_file:
      - ./bot_service/.env
    command: bash -c "make"
    volumes:
      - ./bot_service:/app
    ports:
      - 8001:8000
      - 443:443

  redis_service:
    image: redis:6
    container_name: redis_service
    command: redis-server --appendonly yes
    volumes:
      - ./redis_service:/data
    restart: on-failure
    ports:
      - 6379:6379

  db_service:
    build: ./db_service
    container_name: db_service
    restart: on-failure
    env_file:
      - .env
    command: bash -c "make"
    volumes:
      - ./db_service:/app
    ports:
      - 8000:8000 # to be hidden in prod

  postgres_service:
    image: postgres:16
    container_name: postgres_service
    restart: on-failure
    env_file: .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer_service
    restart: always
    ports:
      - 8080:8080
